# cwd: ../templates
...@neutral-theme
direction: down

web: Web app {class: actor}
aws: AWS {
  class: zone
  api: Upload API {class: service}
  s3: "Images bucket\nS3" {class: datastore}
  db: "Upload records\nDynamoDB" {class: datastore}
  worker: "Thumbnail worker\nLambda" {class: [service; focal]}
}

web -> aws.api: gets presigned URL {class: dep}
web -> aws.s3: uploads image {class: dep}
aws.api -> aws.db: records upload {class: dep}
aws.s3 -> aws.worker: S3 event {class: async}
aws.worker -> aws.s3: writes 3 thumbnails {class: dep}
