# k8s icons for resources, lucide in the k8s blue for the rest (FIXPLAN D6)
...@mini-theme
direction: down
inet: Internet {class: service; icon: icons/globe-k8s.svg}
pod: Pod {class: service; icon: icons/k8s-pod.svg}
inet -> pod: HTTPS {class: dep}
