# a slate lucide icon beside a k8s one
...@mini-theme
direction: down
inet: Internet {class: service; icon: icons/globe-slate.svg}
pod: Pod {class: service; icon: icons/k8s-pod.svg}
inet -> pod: HTTPS {class: dep}
