vars: {
  d2-config: {
    theme-id: 101
    dark-theme-id: 200
  }
}

api: API
db: Database

api.style.fill: "#E3F2FD"
api.style.stroke: "#1565C0"
api.style.font-size: 18
api.style.bold: true

db.shape: cylinder
db.style.fill: "#FFF8E1"
db.style.stroke: "#EF6C00"

api -> db
