// Round-5 held-out requests for the d2-diagram skill (dev only; never copied into the skill).
// Same shape as eval/eval2.js REQ: id -> the user's request, verbatim.
// Spread: architecture, deployment, sequence, state, ERD, flowchart, pipeline, C4,
// code-annotated, code-compare. No domain is shared with a benchmark request or with any
// worked example after the FIXPLAN F28 replacements (checked by dev/tests/structure check (r)).
export default {
  'video-arch': 'Architecture diagram of our video-on-demand platform: TV and web players fetch playlists and video segments from a CDN; the Playback API checks the viewer\'s entitlement with the Subscriptions service and returns a signed manifest URL; creators upload source files to an Upload service that stores them in object storage and puts a job on a transcoding queue; GPU transcoder workers pull jobs and write HLS renditions back to object storage; a DRM license server (external) issues content keys to the players. Group into zones: clients, edge, services, media processing, external. SVG for the engineering handbook.',
  'gke-inference': 'Deployment diagram of our ML inference service on Google Cloud: a global load balancer sends traffic to a GKE cluster; in the gateway namespace an Envoy gateway Deployment (2 replicas) routes to the inference namespace, which runs a model-server Deployment with 4 GPU replicas and a CPU fallback Deployment with 2 replicas, each behind its own Service; model-server pods pull model weights from a GCS bucket at startup and read an API key from Secret Manager; request logs go to Pub/Sub and on to BigQuery. GCS, Secret Manager, Pub/Sub and BigQuery are managed services outside the cluster. Show the cluster and both namespaces. SVG for our runbook.',
  'totp-sequence': 'Sequence diagram of our login with two-factor authentication between the Browser, the Web app, the Auth service and the User DB: the user submits email and password; the Auth service loads the user and checks the password hash; if 2FA is enabled it returns a challenge instead of a session; the browser posts the 6-digit TOTP code; the Auth service verifies it against the stored secret and issues a session cookie. After 5 wrong codes the account is locked and the user sees a "try again in 15 minutes" error. Show both the success path and the lockout path. SVG for the security docs.',
  'claim-state': 'State machine of an insurance claim: submitted -> under review -> approved -> paid. Under review can ask the customer for more information (waiting for customer); when the customer responds it goes back to under review, and after 30 days without a response the claim is closed. Under review can also reject the claim. The customer can withdraw a claim while it is submitted or under review. Paid, rejected, closed and withdrawn are terminal. Mark the initial and terminal states and label every transition with its event. SVG for the claims team wiki.',
  'library-erd': 'ER diagram for a library lending system: branches; books (isbn, title, author); copies (each physical copy of a book has a barcode and belongs to a branch); members; loans (a member borrows a copy, with loaned_at, due_at, and returned_at which stays null until the copy comes back); reservations (a member reserves a book, not a specific copy, with a queue position). Show primary and foreign keys, column types and the cardinality of every relationship. SVG for the README.',
  'expense-flow': 'Flowchart of our expense reimbursement process: an employee submits an expense report; the system checks receipts (every item over $75 needs one) and per-diem limits in parallel; if a check fails the report goes back to the employee to fix and resubmit; then the manager approves or rejects it; reports over $5,000 also need the finance director\'s approval; approved reports are paid in the next payroll run and the employee is notified; a rejected report is closed with the reason. SVG for the finance wiki (an ~800px wide column).',
  'iot-pipeline': 'Data pipeline diagram for our smart-meter telemetry on AWS: meters publish readings over MQTT to AWS IoT Core; an IoT rule forwards them to a Kinesis data stream; a Lambda validator writes good readings to Timestream and bad ones to a dead-letter S3 bucket; a nightly Glue job aggregates Timestream into Parquet files on S3 that Athena queries; Grafana dashboards read Timestream for live views and the billing service queries Athena for monthly usage. SVG for the platform design doc.',
  'clinic-c4': 'C4 container diagram for a clinic appointment booking system: patients use a patient web portal and a mobile app, and clinic staff use a back-office web app; all three call the Booking API; the API reads and writes the appointments database, publishes reminder jobs to a message queue that a Reminder worker consumes to send SMS through Twilio (external), and syncs doctors\' schedules with the existing electronic health record system (external). Show the system boundary. SVG for an architecture review.',
  'ratelimit-code': 'Annotate this Go method from our rate limiter for the onboarding guide: explain the lock, the refill from elapsed time, the cap at capacity, and the reject path. SVG for an ~800px docs column.\n```go\nfunc (b *Bucket) Allow() bool {\n\tb.mu.Lock()\n\tdefer b.mu.Unlock()\n\tnow := time.Now()\n\telapsed := now.Sub(b.last).Seconds()\n\tb.tokens = math.Min(b.capacity, b.tokens+elapsed*b.rate)\n\tb.last = now\n\tif b.tokens < 1 {\n\t\treturn false\n\t}\n\tb.tokens--\n\treturn true\n}\n```',
  'fetch-compare': 'For our PR description, show the before and after of the fix in our React UserCard component and explain why it changed: a slow response for an old id could overwrite the newer user, and the request kept running after the component unmounted. SVG.\nBefore:\n```tsx\nuseEffect(() => {\n  fetch(`/api/users/${id}`)\n    .then((r) => r.json())\n    .then(setUser);\n}, [id]);\n```\nAfter:\n```tsx\nuseEffect(() => {\n  const ctrl = new AbortController();\n  fetch(`/api/users/${id}`, { signal: ctrl.signal })\n    .then((r) => r.json())\n    .then(setUser)\n    .catch(() => {});\n  return () => ctrl.abort();\n}, [id]);\n```',
}
